// Generated by CoffeeScript 1.12.4
var DO, colors, fs, https, request;

https = require('https');

fs = require('fs');

colors = require('colors');

request = require('request');

DO = {
  getDropletInfo: function(options) {
    var callback, headers;
    headers = {
      'Content-Type': 'application/json',
      'Authorization': 'Bearer ' + config.keys.digital_ocean.apiToken
    };
    options = {
      url: 'https://api.digitalocean.com/v2/droplets?page=1&per_page=1',
      headers: headers
    };
    callback = function(error, response, body) {
      var data;
      if (!error && response.statusCode === 200) {
        data = JSON.parse(body);
        data.droplets.map(function(droplet) {
          console.log("\n");
          console.log("Name:\t" + droplet.name.cyan);
          console.log("Memory:\t" + droplet.memory);
          console.log("VCPUS:\t" + droplet.vcpus);
          console.log("Disk:\t" + droplet.disk);
          console.log("Status:\t" + (droplet.status === 'active' ? droplet.status.green : droplet.status.red));
          return console.log("\n");
        });
      }
    };
    return request(options, callback);
  },
  __getBilling: function() {
    return console.log("__getBilling()...");
  }
};

module.exports = DO;
